# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: padartech
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: update-empathy-space-server
service: empathy-space-site-api
provider:
  name: aws
  runtime: nodejs18.x
  stage: prod
  region: us-east-1
  memorySize: 128
functions:
  app:
    handler: app/app.handler
    events: 
      - http: 
          path: /
          method: ANY
          cors: true
      - http: 
          path: /{proxy+}
          method: ANY
          cors: true